baseURL = "https://carterjbastian.github.io/"
title = "My New Hugo Site"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
googleAnalytics = "XXX"
disqusShortname = "carterjbastian"
buildDrafts = true

[Author]
    name = "Carter J. Bastian"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/carterjbastian"
    linkedin = "https://www.linkedin.com/in/carterbastian/"
    stackoverflow = "https://stackoverflow.com/users/4390113/carter"
    email = "carter.bastian1@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    posts = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

